common: &common
  adapter: postgresql
  host: localhost
  username: ubuntu
  password: ubuntu
  reconnect: true

development:
  <<: *common
  database: pupilfirst

test:
  <<: *common
  database: pupilfirst_test

production:
  pool: 5
