common: &common
  adapter: postgresql
  host: localhost
  username: ubuntu
  password: ubuntu
  reconnect: true

development:
  <<: *common
  database: pupilfirst_dev

test:
  <<: *common
  database: pupilfirst_test

production:
  adapter: postgresql
  host: localhost
  database: pupilfirst
  pool: 5
  username: ubuntu
  password: ubuntu